### ISSUE TITLE
Publicly exposing `defaultChunkSize`

### ISSUE THREAD

**Issue by shlok** [haskell-streaming/streaming-bytestring#10]
What do you think about publicly exposing `defaultChunkSize`?

Use case: This would allow me to write an `Arbitrary` instance for strict `ByteString`s that is more likely to generate `ByteString`s of lengths around the chunk size. I imagine such bytestrings would be more useful when `QuickCheck`ing code involving both strict and streaming bytestrings.

**Comment by fosskers** [comment]
Looking through the code, I see `defaultChunkSize` used in 4 places. Is it that you'd like more control over `toStreamingByteString` in a way that `toStreamingByteStringWith` doesn't already allow?

**Comment by shlok** [comment]
It turns out I was headed in the wrong direction. I didn’t realize that the chunk structure was actually preserved when using, e.g., `fromChunks`. Apologies, and thanks for your time.
