### ISSUE TITLE
Laziness of `toLazy` in IO and Identity

### ISSUE THREAD

**Issue by YPares** [haskell-streaming/streaming-bytestring#11]
I'm under the impression that `toLazy` will actually build in memory the whole lazy bytestring --and therefore that code running it won't run in constant memory-- if the underlying monad's `(>>=)` isn't lazy itself (because toLazy is generic in the monad, it can't use unsafeInterleaveIO). At least it is the case for `toList` in `streaming`.

If that's the case, could it be made clearer in the documentation?

**Comment by limaner2002** [comment]
I was just thinking about this, ran the following in `ghci` and found that it does indeed strictly evaluate in IO.

>>>
> str <- Q.toLazy $ Q.repeat 42
>>>

**Comment by YPares** [comment]
After coming back to it, it seems that `toLazy` isn't even lazy in `Identity`:

```
toLazy :: Monad m => ByteString m r -> m (Of BI.ByteString r)
toLazy bs0 = dematerialize bs0
                (\r -> return (BI.Empty :> r))
                (\b mx -> do 
                      (bs :> x) <- mx 
                      return $ BI.Chunk b bs :> x
                      )
                join
```

The cons function executes `mx` and uses a refutable pattern. So the evaluation of `mx` will always occur before the `b` in `BI.Chunk b bs` can ever be evaluated. This makes this operation stricter than it needs to be. It probably shoud be:

`                      ~(bs :> x) <- mx`

What do you think?

**Comment by andrewthad** [comment]
Here's my perspective on this. The "lazy" `ByteString` and `Text` types (from `bytestring` and `text` respectively) are strange. They are used both for the purpose of lazy IO (which is largely considered unsound) and as a specialization of List where the element type is a chunk of bytes/text (which is certainly sound). Interestingly, the `Builder` type corresponding to each of these also does some `unsafeInterleaveIO`/`unsafeInterleaveST` to get some additional laziness in places where it wouldn't normally be possible to be lazy. But there are other ways people use these types. In `http-client`, for example, lazy `ByteString` is used as the target for an HTTP response, but it doesn't do lazy IO. That is, all the chunks are evaluated. We end up with a repurposing where there's a type that was originally intended for a particular purpose, but people have largely abandoned the original paradigm into which it fit.

I'd take a PR adding irrefutability to the pattern match. The extra laziness will only matter when working in `Identity`. Realistically, I doubt that any users of `streaming` are working in `Identity`, so I don't think this will impact anyone in a surprising way.

**Comment by vdukhovni** [comment]
My take is that actual laziness is actually rather undesirable here. The purpose of `toLazy` is in fact to bring all the chunks into memory, but without paying the cost of copying them into a single buffer. They can then be passed around between threads via channels, or other processed without any latent monadic effects.

Since in fact `toLazy` is just a way to produce a "rope" (list of chunks) rather than a string (single buffer), the current behaviour is the correct one. My advice is to close this issue as "won't fix".

**Comment by fosskers** [comment]
@YPares please feel free to reopen this if there is a pressing need.
