### ISSUE TITLE
Advice about how to properly chunk a file

### ISSUE THREAD

**Issue by mpickering** [haskell-streaming/streaming-bytestring#12]
I want to read a csv file incrementally so I need to split it into chunks breaking on commas and newlines. 
The way I do this for various reasons is with calls to `takeWhile` and `dropWhile`. This creates a file with thousands of chunks.

The problem arose because I tried to run this program on a `ByteString` created with `readFile`, I ran out of file handles because the file was being opened and not closed for each chunk. 

To fix this, I created my own variant of `readFile` which used `openFile` in combination with `fromHandle` to create a single handle at the start which is then used for all subsequent reads. 

Is there a variant of `readFile` which already does this? Could a version like this be added to the library in a way which interacts well with `ResourceT`?

**Comment by fosskers** [comment]
You might instead consider [streaming-attoparsec](https://hackage.haskell.org/package/streaming-attoparsec). There are examples in its docs of how to use it in tandem with `streaming-bytestring`.

**Comment by mpickering** [comment]
`streaming-attoparsec` is at too high-level of abstraction as I need to be able to manipulate the chunks.

**Comment by fosskers** [comment]
Perhaps a single `readFile` call, followed by usage of [splitWith](http://hackage.haskell.org/package/streaming-bytestring-0.1.6/docs/Data-ByteString-Streaming-Char8.html#v:splitWith)?

**Comment by andrewthad** [comment]
> The way I do this for various reasons is with calls to `takeWhile` and `dropWhile`... The problem arose because I tried to run this program on a `ByteString` created with `readFile`, I ran out of file handles because the file was being opened and not closed for each chunk.

My understanding of what you described is that you made repeated calls to `readFile` and then sliced into each one using `takeWhile` and `dropWhile`. This largely defeats the purpose of the abstraction `streaming-bytestring` provides. Even if the file descriptor leaking wasn't a problem, your number of disk reads is quadratic in the size of your file (assuming a high number of chunks). I'm not sure if my interpretation of your description is correct, but it sounds like your running out of file descriptors while processing a single file.

> Is there a variant of `readFile` which already does this? Could a version like this be added to the library in a way which interacts well with `ResourceT`?

I think `readFile` is the function you are looking for. If your able to share your code, it would make it easier to know what's going on.

**Comment by mpickering** [comment]
I think you're definitely right that I'm violating the xen of `streaming-bytestring`. I've realigned by program now so that it fits in better with the library. 

Now I'm creating a `Stream (ByteString ResIO) ResIO ()` by using `splitAt`. Then I want to keep every other chunk, is there a way to do this with a combinator? `filter` is not what I want as I don't want to read the bytestring. It seems like I could use something form `Streaming.Internal` with `effects` to achieve this?

**Comment by andrewthad** [comment]
I think that you want

    scan :: Monad m => (x -> a -> x) -> x -> (x -> b) -> Stream (Of a) m r -> Stream (Of b) m r

You can do something like

    scan (\prev next -> maybe (Just next) (\_ -> Nothing) prev) Nothing (fromMaybe Data.ByteString.Streaming.empty)

I think that will drop every other element.

**Comment by mpickering** [comment]
Thanks for your help.
