### ISSUE TITLE
Improve null checking documentation

### ISSUE THREAD

**Issue by treeowl** [haskell-streaming/streaming-bytestring#13]
The fundamental test for whether a stream is empty is `testNull`, which is undocumented, placed below `null` and `null_` in the export list, and separated from them by the very different `nulls`. I think `testNull` should probably come first. `null_` might be confusing for beginners. They may not realize that it should be seen as fully consuming a stream (which normally shouldn't be used again). I think it would make sense to explain in the module documentation the distinction between functions that fully consume the stream and ones that don't.

**Comment by fosskers** [comment]
Let me take a look at this.

**Comment by fosskers** [comment]
This should be clearer now due to recent documentation improvements over the whole library.
