### ISSUE TITLE
intersperse doesn't work

### ISSUE THREAD

**Issue by ocharles** [haskell-streaming/streaming-bytestring#2]
`intersperse` ends up just adding the bytestring to every element, rather than everything but the last element. There is a comment in the code that it "isn't quite right", which appears to be true.

**Comment by andrewthad** [comment]
I'll take a PR to fix this.

**Comment by fosskers** [comment]
Is this still an issue?

**Comment by vdukhovni** [comment]
This should be fixed by #42 

[ I'm assuming the issue was actually about `intercalate`, which had the reported issue and the "this isn't quite right" comment, unlike `intersperse`. ]

**Comment by vdukhovni** [comment]
I think this issue can be closed.

**Comment by fosskers** [comment]
I've linked your PR, so that this issue will be closed automatically once it is merged.
