### ISSUE TITLE
multiple copies of code in source tree

### ISSUE THREAD

**Issue by chessai** [haskell-streaming/streaming-bytestring#34]
looks like we have

```
❯ tree lib
lib
├── Data
│   └── ByteString
│       ├── Streaming
│       │   ├── Char8.hs
│       │   └── Internal.hs
│       └── Streaming.hs
└── Streaming
    ├── ByteString
    │   ├── Char8.hs
    │   └── Internal.hs
    └── ByteString.hs

5 directories, 6 files
```

Where each module in `Data/ByteString/` and `Streaming/` are equivalent. What is the reason for the duplication?

**Comment by chessai** [comment]
Is the idea to deprecate the old `Data.ByteString.*` modules in favour of the new ones, while keeping both around?

**Comment by chessai** [comment]
Ah, I forgot about this. Yes, that is the point (as indicated by the deprecation pragmas). Deprecations require a majour version bump - so we would need to bump to 0.2.

**Comment by fosskers** [comment]
Ah, I didn't bump it on purpose because there were technically no breaking changes. I was going off of SemVer logic - is PVP different on that particular issue?
