### ISSUE TITLE
next version must be a majour version bump

### ISSUE THREAD

**Issue by chessai** [haskell-streaming/streaming-bytestring#35]
because we are deprecating Data.ByteString.* and the ByteString type, the next version bump must be majour, meaning we can no longer stay on 0.1.*. Then, after a suitable deprecation period, there would be another majour version bump which removes the deprecated modules.

**Comment by vdukhovni** [comment]
If this a major version bump, perhaps some outstanding nits that require interface changes to fix can be addressed?  If so, this is a good time to go over the API and hunt down the warts...

**Comment by fosskers** [comment]
I wouldn't mind, if they are small things.

**Comment by vdukhovni** [comment]
> I wouldn't mind, if they are small things.

I'll do my best to identify the appropriate candidates.  The first step might be #39 (not even a compatibility issue, since we're making the input type more polymorphic).

**Comment by vdukhovni** [comment]
But do you have any comments about #40? That might require an API change if the idea is to make the Char8 and Word8 interfaces consistent...

**Comment by vdukhovni** [comment]
OK, #42 is my take on the requisite changes. Please review.

But #42 does not subsume #40, or the other issues I opened, so feedback on those would be great. (But it does take care of #37).

**Comment by vdukhovni** [comment]
Before the major version bump, it may make sense to release 0.1.8 with #43 (sorry about the bug, one edge case the tests did not catch). Code coverage does not complain about incorrectly ignored `_` variables... :-(

**Comment by fosskers** [comment]
I think it would be okay to just go ahead with `0.2` when your fix is included, since apparently it was my mistake to have only bumped the minor version.

**Comment by vdukhovni** [comment]
Yeah, I wondered about that.  Works for me at this point.

**Comment by fosskers** [comment]
Done.

In 6 - 12 months when we dump the deprecations, I suggest we move to `1.0.0` to celebrate the overhauled module paths.
