### ISSUE TITLE
Support efficient withForeignPtr for GHC 9.0.1?

### ISSUE THREAD

**Issue by vdukhovni** [haskell-streaming/streaming-bytestring#48]
In GHC 9.0.1 regular withForeignPtr incurs a performance penalty that can be avoided for actions that can't diverge. We may want to adopt changes similar to those in [bytestring](https://github.com/haskell/bytestring/commit/36c2df1feaf10fde8d5848ac47b98d6d62c4e1d7#diff-4105c07a81270ce44ac897cada298da7e98475c346100e92b1e1951b0484c4bcL143-L145)

**Comment by vdukhovni** [comment]
I opened #53 to resolve this issue.

[ P.S. lts-6.35 CI seems to be failing for all commits, perhaps just drop it from the matrix? ]

**Comment by fosskers** [comment]
I've noticed the `lts-6` issue and tried to debug it, but couldn't replicate it locally. I might just drop it from the Matrix after all.
