### ISSUE TITLE
Disabled in Stackage nightly

### ISSUE THREAD

**Issue by ocramz** [haskell-streaming/streaming-bytestring#62]
I\ve just received notice that SB fails to build due to an upper bound on ghc-prim .

https://github.com/commercialhaskell/stackage/blob/11e033b0c4eaea8ef32adf457746d4bec0321514/build-constraints.yaml#L7427  , " streaming-bytestring < 0 # tried streaming-bytestring-0.2.1, but its *library* does not support: ghc-prim-0.8.0"

Could it be a case for updating Hackage metadata or is it a deeper change?

**Comment by fosskers** [comment]
I will fix this tomorrow.

**Comment by fosskers** [comment]
Thanks for your patience, I've just uploaded `0.2.2` to Hackage.
