### ISSUE TITLE
[Request] Release 0.1.6

### ISSUE THREAD

**Issue by fosskers** [haskell-streaming/streaming-bytestring#7]
Which includes the `Semigroup` instance for `ByteString m r`, so that we can unblock a number of stackage issues.

**Comment by andrewthad** [comment]
I've given you write access to `streaming-bytestring`, and I've added you as a maintainer for the package on hackage. If you don't mind, could you do the release?

**Comment by fosskers** [comment]
Sure! Thank you kindly.

**Comment by andrewthad** [comment]
Thanks!

**Comment by fosskers** [comment]
Released as `0.1.6` (backwards-compatible API change).
