### ISSUE TITLE
New Hackage release with GHC 9.4.4 support?

### ISSUE THREAD

**Issue by thomasjm** [haskell-streaming/streaming-bytestring#70]
It looks like this is working on the current `master` branch. I think #69 can be closed also. Thanks for the awesome library!

**Comment by fosskers** [comment]
Thanks. Right, we had already fixed this in https://github.com/haskell-streaming/streaming-bytestring/pull/68 but hadn't done a release yet. We were considering dropping support for 7.10 before doing so. @vdukhovni shall we just pull the trigger?

**Comment by vdukhovni** [comment]
Yes. Anything older than 8.0 is no longer viable (or at least no longer can expect updates).

**Comment by fosskers** [comment]
Great. Then I will take care of this tomorrow morning (Friday).
