### ISSUE TITLE
toLazy_ allows to construct a malformed ByteString

### ISSUE THREAD

**Issue by Bodigrim** [haskell-streaming/streaming-bytestring#76]
```haskell
> chunkMap (const mempty) "bar"
Chunk "" (Empty (()))
> toLazy_ $ chunkMap (const mempty) "bar"
""
> Data.ByteString.Lazy.null <$> (toLazy_ $ chunkMap (const mempty) "bar")
False
```

`toLazy_` should use [`chunk`](https://hackage.haskell.org/package/bytestring-0.12.1.0/docs/Data-ByteString-Lazy-Internal.html#v:chunk) instead of [`Chunk`](https://hackage.haskell.org/package/bytestring-0.12.1.0/docs/Data-ByteString-Lazy-Internal.html#t:ByteString), otherwise the result violates [internal invariants of lazy `ByteString`](https://hackage.haskell.org/package/bytestring-0.12.1.0/docs/src/Data.ByteString.Lazy.Internal.html#ByteString) (namely, contains an empty `Chunk`).

(Additionally, `chunkMap` should probably skip empty chunks)

**Comment by fosskers** [comment]
Nice find. How did you discover this?

**Comment by Bodigrim** [comment]
A bug was reported to me privately.

**Comment by fosskers** [comment]
Thanks again for reporting.
