### ISSUE TITLE
Update documentation of `hGetContents` and `hGetContentsN`.

### ISSUE THREAD

**Issue by danidiaz** [haskell-streaming/streaming-bytestring#9]
The documentation states the following about `hGetContents` and `hGetContentsN`:

> The handle is closed on EOF.

Looking at the code, that doesn't seem to be the case. And that is good! It makes more sense this way and fits better with how `pipes-bytestring` works. So perhaps the documentation should be updated, removing the references to handles being closed on EOF.

**Comment by fosskers** [comment]
Fixed. Sorry this took so long to do.
